name: 'Facto'
description: 'end-to-end tests'
author: 'SZ'
inputs:
  config:
    description: 'configuration values'
    required: false
  config-file:
    description: 'Path to a JSON file where configuration values are set.'
    required: false
    default: cypress.json
  env:
    description: 'Sets Cypress environment variables'
    required: false
  browser:
    description: 'Name of the browser to use'
    required: false
  command:
    description: 'Command that overrides cypress run'
    required: false
runs:
  using: 'node12'
branding:
  color: 'green'
  icon: 'check-square'