

name: tags
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E
    steps:
      - name: Test
        run: |
          npm install
          npm ci
          npm run cy:ci
        with:
          browser: chrome
          headless: true