

name: tags
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E
    steps:
      - name: Test
        uses: actions/setup-node@v1
        with:
          browser: chrome
          headless: true
      - run: |
        npm install
        npm ci
        npm run cy:ci