
name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
      with:
        browser: chrome
        headless: true
    - name: Run a one-line script
      run: 
        - npm install
        - npm ci
        - npm run cy:ci