

name: tags
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          browser: chrome
          headless: true
      - run: node -v