name: chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Chrome headless
        uses: ./
        with:
          working-directory: examples/chrome
          browser: chrome
          headless: true
          
      - run: npm install
      - run: npm run cy:ci
        working-directory: ./