name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Chrome headless
        uses: ./
        with:
          working-directory: ./
          browser: chrome
          headless: true