name: example-chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Chrome headless
        uses: ./
        with:
          working-directory: ./
          browser: chrome
          headless: true
