name: chrome
on: 
  schedule:
    - cron: "" 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          employee_id: ${{ secrets.employee_id }}
        run: |
          npm install
          npm run cy:ci
        working-directory: ./

