name: chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: tests
        run: |
          npm install
          npm ci
          npm run cy:ci
        working-directory: ./
