name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: factorial-checkin/github-action@v1
        with:
          browser: chrome
          headless: true